use soroban_sdk::{
    contract, contractimpl, panic_with_error, symbol_short, token, Address, Bytes, Env, String,
    Symbol, Vec, contracttype,
};

use crate::{
    admin, balance,
    errors::VaultError,
    events,
    nft::StakeReceiptNFTClient,
    storage::{
        AccessTier, AdminAction, AdminProposal, AuctionBid, AutoConvertConfig, BoostTierProgress,
        BootstrapConfig, BrandingConfig, CampaignInfo, CapacityAuction, ChangelogEntry, ClaimWindow,
        ContractAddresses, ContractMetadata, DataKey, DayBucket, DebtNFT, DelegationChain, DynamicFeeConfig,
        EpochState, FeeRecipient, FlashStakeReceipt, GovernanceProposal, HalvingConfig,
        InsurancePolicy, InsuranceProduct, InterfaceId, LeaderboardEntry, Loan, LoanConfig,
        LotteryConfig, MerkleRoot, MigrationExport, Milestone, MilestoneCondition, MultisigConfig,
        OptimalClaimAdvice, PauseInfo, PauseReason, PendingAction, PoolComparison, PoolConfig,
        OperatorDashboard, PoolHealthReport, PoolStats, PredictionMarket, PriceCondition, PriorityBidRecord, ProposableParam,
        RateHistoryEntry, ReferralLeaderboardEntry, ReferralTreeNode, ReputationScore, RewardTier,
        RewardMultiplierBreakdown, RevenueShareMerkleRoot, RevenueSharingConfig, RoundingPolicy,
        Season, SmoothingSchedule, SmoothingStatus,
        StakeAction, StakeHistoryEntry, StakePosition, StakeStreak, StakingCertificate,
        StakingEfficiencyScore, StorageUsageReport, SunsetState, SwapOffer, TaxReport, Tournament,
        TriggerDirection, UnbondingPosition, UnstakeCheckResult, UserStats, UserSummary,
        VestingEntry, YieldComparison,
    },
};

/// Minimal interface for the Stellar DEX router `swap_and_stake` calls into
/// (issue #205). This contract doesn't own or embed a DEX — it's a thin
/// client for whatever router contract the admin configures via
/// `set_dex_router()`, so any router implementing this same function
/// signature (a common shape for Soroban AMM/router contracts) works.
///
/// `swap` must pull `amount_in` of `from_token` from the caller (this vault
/// contract, which pre-funds itself via `input_token`'s own `transfer` in
/// `swap_and_stake` before calling this), and deliver at least
/// `min_amount_out` of `to_token` to `to`, reverting otherwise.
// Only `DexRouterClient`, generated by `contractclient`, is ever called; the
// trait itself exists to declare that client's shape.
#[allow(dead_code)]
#[soroban_sdk::contractclient(name = "DexRouterClient")]
pub trait DexRouterInterface {
    fn swap(
        env: Env,
        from_token: Address,
        to_token: Address,
        amount_in: i128,
        min_amount_out: i128,
        to: Address,
    ) -> i128;
}

/// Maximum number of stake/unstake history entries kept per user (issue #105).
pub(crate) const MAX_STAKE_HISTORY: u32 = 5;
/// Maximum number of admin changelog entries retained (issue #114).
pub(crate) const MAX_CHANGELOG_ENTRIES: u32 = 10;

pub(crate) const CONTRACT_VERSION: &str = "0.1.0";
pub(crate) const CONTRACT_NAME: &str = "stellar-staking-pool";
pub(crate) const CONTRACT_DESCRIPTION: &str =
    "A staking pool contract for Stellar DeFi vault positions.";
pub(crate) const BOOST_BPS_BASE: u32 = 10_000;
pub(crate) const MAX_BOOST_TIERS: u32 = 5;
pub(crate) const MAX_HISTORY_SNAPSHOTS: u32 = 100;
pub(crate) const STELLAR_LEDGERS_PER_YEAR: u32 = 6_307_200;
pub(crate) const MAX_UNSTAKE_FEE_BPS: u32 = 500;
/// Approximate number of Stellar ledgers in one day at 5 s/ledger (issue #133).
pub(crate) const LEDGERS_PER_DAY: u32 = 17_280;
/// Days of runway below which a refill alert is emitted.
pub(crate) const REFILL_ALERT_DAYS: u32 = 30;
/// Fraction of total_staked reserved as a liquidity buffer, never deployed to
/// yield (issue #215). 20% in basis points.
pub(crate) const YIELD_BUFFER_BPS: u32 = 2_000;
/// Maximum number of simultaneously open governance proposals (issue #216).
pub(crate) const MAX_OPEN_PROPOSALS: u32 = 10;
/// Maximum number of milestones an admin may configure (issue #238).
pub(crate) const MAX_MILESTONES: u32 = 10;
/// Estimated gas cost for a first-time stake transaction (issue #204).
pub(crate) const FIRST_STAKE_COST: u64 = 100_000;
/// Estimated gas cost for a top-up stake transaction (issue #204).
pub(crate) const TOP_UP_COST: u64 = 50_000;
/// Maximum sub-score for any single reputation dimension (2500 = 25% of total 10 000).
pub(crate) const REPUTATION_SUB_SCORE_MAX: u32 = 2500;
/// Points deducted per lifetime claim (100 bps = 1% of max consistency score).
pub(crate) const REPUTATION_CLAIM_DECAY_BPS: u32 = 100;
/// Longest window a reward addition may be smoothed over — one year (issue #235).
pub(crate) const MAX_SMOOTHING_PERIOD_LEDGERS: u32 = STELLAR_LEDGERS_PER_YEAR;
/// Deepest referral level `referral_tree_data` will walk (issue #236).
pub(crate) const MAX_REFERRAL_TREE_DEPTH: u32 = 3;
/// Hard cap on nodes returned by `referral_tree_data`, bounding its read cost
/// on a wide tree (issue #236).
pub(crate) const MAX_REFERRAL_TREE_NODES: u32 = 50;
/// Most pool spots a single capacity auction may allocate (issue #237).
pub(crate) const MAX_AUCTION_SPOTS: u32 = 20;
/// Most distinct bidders one capacity auction accepts (issue #237).
pub(crate) const MAX_AUCTION_BIDS: u32 = 50;
/// Most `PriorityBidRecord` entries `get_priority_bids()` retains; oldest is
/// evicted once full (issue #251).
pub(crate) const MAX_PRIORITY_BID_RECORDS: u32 = 50;
/// Field length caps for `set_branding()`, in bytes (issue #258). `logo_hash`
/// is sized for a SHA-256 hex digest.
pub(crate) const MAX_BRANDING_NAME_LEN: u32 = 50;
pub(crate) const MAX_BRANDING_LOGO_LEN: u32 = 64;
pub(crate) const MAX_BRANDING_URL_LEN: u32 = 200;
pub(crate) const MAX_BRANDING_TWITTER_LEN: u32 = 16;
/// Most users a single `declare_shortfall()` call may pay out to (issue #259).
pub(crate) const MAX_SHORTFALL_USERS: u32 = 50;
/// LTV, in basis points, at or above which `liquidate_loan()` is permitted
/// (issue #261).
pub(crate) const LIQUIDATION_LTV_BPS: u32 = 9_000;
/// Most active stakers `get_reward_gini_coefficient()` will process in one
/// call before reverting with `TooManyStakers` (issue #275).
pub(crate) const MAX_GINI_STAKERS: u32 = 100;
/// Most seasons `add_season()` will keep scheduled at once (issue #276).
pub(crate) const MAX_SEASONS: u32 = 10;
/// Longest allowed `set_staker_bio()` bio, in bytes (issue #274).
pub(crate) const MAX_BIO_LEN: u32 = 160;

/// Max waitlist size cap (Acceptance Criteria #7)
pub(crate) const MAX_WAITLIST_SIZE: u32 = 100;

#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WaitlistEntry {
    pub user: Address,
    pub intended_amount: i128,
    pub joined_waitlist_at: u32,
}

#[contract]
pub struct VaultContract;

#[contractimpl]
impl VaultContract {
    /// Initialize the vault with an admin and the token it accepts.
    pub fn initialize(
        env: Env,
        admin: Address,
        token: Address,
        reward_rate_bps: u32,
        _stake_decimals: Option<u32>,
        _reward_decimals: Option<u32>,
    ) -> Result<(), VaultError> {
        if env.storage().instance().has(&symbol_short!("admin")) {
            panic_with_error!(&env, VaultError::AlreadyInitialized);
        }

        env.storage().instance().set(&symbol_short!("admin"), &admin);
        env.storage().instance().set(&symbol_short!("token"), &token);
        env.storage().instance().set(&symbol_short!("rate"), &reward_rate_bps);
        env.storage().instance().set(&symbol_short!("paused"), &false);
        
        // Mock default current capacity metrics for testing pool caps
        env.storage().instance().set(&symbol_short!("cur_stk"), &1_000_000_i128);
        env.storage().instance().set(&symbol_short!("max_cap"), &1_000_000_i128);

        Ok(())
    }

    /// Stakes `amount` of the pool's token on behalf of `user`, minting
    /// shares proportional to the current share price (1:1 for the pool's
    /// first deposit). Returns the number of shares minted.
    pub fn stake(env: Env, user: Address, amount: i128) -> Result<i128, VaultError> {
        user.require_auth();
        if amount <= 0 {
            return Err(VaultError::ZeroAmount);
        }

        let token_addr: Address = env
            .storage()
            .instance()
            .get(&symbol_short!("token"))
            .ok_or(VaultError::NotInitialized)?;
        token::Client::new(&env, &token_addr).transfer(
            &user,
            &env.current_contract_address(),
            &amount,
        );

        let total_shares = balance::get_total_shares(&env);
        let total_deposited = balance::get_total_deposited(&env);
        let shares_minted = if total_shares == 0 || total_deposited == 0 {
            amount
        } else {
            amount
                .checked_mul(total_shares)
                .and_then(|v| v.checked_div(total_deposited))
                .ok_or(VaultError::ArithmeticError)?
        };

        let current_shares = balance::get_shares(&env, &user);
        balance::set_shares(&env, &user, current_shares + shares_minted);
        balance::set_total_shares(&env, total_shares + shares_minted);
        balance::set_total_deposited(&env, total_deposited + amount);

        Ok(shares_minted)
    }

    /// Sets or replaces the secondary emergency admin address.
    pub fn set_emergency_admin(env: Env, new_emergency_admin: Address) -> Result<(), VaultError> {
        let primary_admin = admin::get_admin(&env)?;
        primary_admin.require_auth();

        env.storage().instance().set(&symbol_short!("em_admin"), &new_emergency_admin);

        env.events().publish(
            (symbol_short!("emer_set"),),
            new_emergency_admin,
        );

        Ok(())
    }

    /// Revokes the current emergency admin address.
    pub fn revoke_emergency_admin(env: Env) -> Result<(), VaultError> {
        let primary_admin = admin::get_admin(&env)?;
        primary_admin.require_auth();

        if env.storage().instance().has(&symbol_short!("em_admin")) {
            env.storage().instance().remove(&symbol_short!("em_admin"));

            env.events().publish(
                (symbol_short!("emer_rvk"),),
                (),
            );
        }

        Ok(())
    }

    /// Adds user to waitlist FIFO queue when pool is at cap.
    pub fn join_waitlist(env: Env, user: Address, intended_amount: i128) -> Result<(), VaultError> {
        user.require_auth();

        let current_staked: i128 = env.storage().instance().get(&symbol_short!("cur_stk")).unwrap_or(0);
        let max_capacity: i128 = env.storage().instance().get(&symbol_short!("max_cap")).unwrap_or(0);

        // Enforce Criteria #8: join_waitlist reverts with PoolNotFull if pool still has capacity
        if current_staked < max_capacity {
            panic_with_error!(&env, VaultError::PoolNotFull);
        }

        let mut queue: Vec<WaitlistEntry> = Self::get_waitlist(env.clone());

        // Enforce Criteria #7: Max waitlist size 100 — revert beyond that
        if queue.len() >= MAX_WAITLIST_SIZE {
            panic_with_error!(&env, VaultError::WaitlistFull);
        }

        let entry = WaitlistEntry {
            user: user.clone(),
            intended_amount,
            joined_waitlist_at: env.ledger().sequence(),
        };

        queue.push_back(entry);
        env.storage().instance().set(&symbol_short!("waitlist"), &queue);

        env.events().publish(
            (symbol_short!("wl_join"), user),
            (intended_amount, env.ledger().sequence()),
        );

        Ok(())
    }

    /// Read-only query for the current waitlist FIFO queue.
    pub fn get_waitlist(env: Env) -> Vec<WaitlistEntry> {
        env.storage()
            .instance()
            .get(&symbol_short!("waitlist"))
            .unwrap_or(Vec::new(&env))
    }
}

